# Generated by Django 4.0.3 on 2023-06-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraint',
            name='description',
        ),
        migrations.AlterField(
            model_name='constraint',
            name='family',
            field=models.CharField(choices=[('active_users', 'Active Users'), ('recently_active_users', 'Recently Active Users')], max_length=50),
        ),
    ]
