# Generated by Django 4.0.3 on 2023-11-02 11:12

import constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=150)),
                ('detail', models.TextField()),
                ('trace_path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Untouched', 'Untouched'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], default=constants.ContactStatus['untouched'], max_length=15)),
            ],
        ),
    ]
