# Generated by Django 4.2.8 on 2024-02-10 17:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_profiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
