# Generated by Django 4.0.3 on 2023-02-07 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0002_alter_phone_number_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(default='NULL', error_messages={'unique': 'Phone number registered already!'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Email must has to be valid.', regex="^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$")]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email taken.'}, max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Email must has to be valid.', regex="^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$")]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(error_messages={'unique': 'Pick another username.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$', 'Enter a valid username. This value may contain only letters, numbers ', 'invalid')], verbose_name='username'),
        ),
    ]
