# Generated by Django 4.0.3 on 2023-02-07 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepoint',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='point', to=settings.AUTH_USER_MODEL),
        ),
    ]
