# Generated by Django 4.0.3 on 2023-02-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0006_alter_profilepoint_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticprofile',
            name='self_point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics', to='auth2.profilepoint'),
        ),
    ]
