# Generated by Django 4.0.3 on 2023-02-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0007_alter_analyticprofile_self_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepoint',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
