# Generated by Django 4.0.3 on 2023-02-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0008_alter_profilepoint_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='number_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
