# Generated by Django 4.0.3 on 2023-02-09 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0009_phone_number_verified_profile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='access_token',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='refresh_token',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='tokens_updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(error_messages={'invalid_phone': 'Provide proper phone number format!', 'unique': 'Phone number registered already!'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Email must has to be valid.', regex='^\\+\\d{2,3}\\s\\d{5}\\-\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Provide valid email.', 'unique': 'Email taken.'}, max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Email must has to be valid.', regex="^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$")]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='socials',
            field=models.ManyToManyField(related_name='profile', to='auth2.social'),
        ),
        migrations.AlterField(
            model_name='social',
            name='handleId',
            field=models.CharField(max_length=50),
        ),
    ]
