# Generated by Django 4.0.3 on 2023-02-09 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0010_social_access_token_social_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='socials',
        ),
        migrations.AddField(
            model_name='social',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
