# Generated by Django 4.0.3 on 2023-02-10 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0011_remove_profile_socials_social_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticprofile',
            old_name='profile_clicks',
            new_name='profile_views',
        ),
        migrations.AlterField(
            model_name='analyticprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='social',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socials', to=settings.AUTH_USER_MODEL),
        ),
    ]
