# Generated by Django 4.0.3 on 2023-02-10 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0012_rename_profile_clicks_analyticprofile_profile_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marks',
            field=models.ManyToManyField(related_name='marked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
