# Generated by Django 4.0.3 on 2023-02-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0013_profile_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticprofile',
            name='profile_views',
            field=models.ManyToManyField(related_name='viewed', to='auth2.profilepoint'),
        ),
        migrations.RemoveField(
            model_name='analyticprofile',
            name='reports',
        ),
        migrations.AddField(
            model_name='analyticprofile',
            name='reports',
            field=models.ManyToManyField(to='auth2.profilepoint'),
        ),
    ]
