# Generated by Django 4.0.3 on 2023-02-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0014_alter_analyticprofile_profile_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='synced_contacts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analyticprofile',
            name='contacts',
            field=models.ManyToManyField(related_name='contact_in', to='auth2.phone'),
        ),
    ]
