# Generated by Django 4.0.3 on 2023-02-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0015_profile_synced_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='raw_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
