# Generated by Django 4.0.3 on 2023-02-21 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0016_phone_raw_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticprofile',
            name='predicted_tags',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9, ]+$', 'Tags only contain whitespaces or commas along with alphanumerics ', 'invalid')]),
        ),
    ]
