# Generated by Django 4.0.3 on 2023-03-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0017_analyticprofile_predicted_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePicUrl',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
