# Generated by Django 4.0.3 on 2023-03-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0019_alter_profile_marks_alter_profile_reachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticprofile',
            name='social_impressions',
        ),
        migrations.AddField(
            model_name='social',
            name='hits',
            field=models.ManyToManyField(blank=True, null=True, to='auth2.profilepoint'),
        ),
    ]
