# Generated by Django 4.0.3 on 2023-03-17 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0020_remove_analyticprofile_social_impressions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marks',
            field=models.ManyToManyField(blank=True, related_name='marked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reachers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='social',
            name='hits',
            field=models.ManyToManyField(blank=True, to='auth2.profilepoint'),
        ),
    ]
