# Generated by Django 4.0.3 on 2023-03-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0021_alter_profile_marks_alter_profile_reachers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='profilePicUrl',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
