# Generated by Django 4.0.3 on 2023-03-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0022_alter_social_profilepicurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticprofile',
            name='predicted_tags',
        ),
    ]
