# Generated by Django 4.0.3 on 2023-03-19 09:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0023_remove_analyticprofile_predicted_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticprofile',
            name='predicted_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=[], null=True, size=None),
        ),
    ]
