# Generated by Django 4.0.3 on 2023-03-19 19:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0024_analyticprofile_predicted_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticprofile',
            name='predicted_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, null=True, size=None),
        ),
    ]
