# Generated by Django 4.0.3 on 2023-03-19 19:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0025_alter_analyticprofile_predicted_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticprofile',
            name='impressions_timestamps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=list, null=True, size=None),
        ),
    ]
