# Generated by Django 4.0.3 on 2023-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0026_analyticprofile_impressions_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='relogin_required',
            field=models.BooleanField(default=True),
        ),
    ]
