# Generated by Django 4.0.3 on 2023-03-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0027_social_relogin_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='name',
        ),
        migrations.AddField(
            model_name='social',
            name='profile_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
