# Generated by Django 4.0.3 on 2023-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0028_remove_social_name_social_profile_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='tokens_updated_at',
        ),
        migrations.AddField(
            model_name='social',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='social',
            name='profile_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='relogin_required',
            field=models.BooleanField(default=False),
        ),
    ]
