# Generated by Django 4.0.3 on 2023-03-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0029_remove_social_tokens_updated_at_social_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='profilePicUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
