# Generated by Django 4.0.3 on 2023-03-24 11:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0030_alter_social_profilepicurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticprofile',
            name='profile_views_timestamps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='analyticprofile',
            name='reports_timestamps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=list, null=True, size=None),
        ),
    ]
