# Generated by Django 4.0.3 on 2023-03-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0031_analyticprofile_profile_views_timestamps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticprofile',
            options={'permissions': (('can_view', 'Can view analytics'),)},
        ),
    ]
