# Generated by Django 4.0.3 on 2023-03-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0032_alter_analyticprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticprofile',
            options={},
        ),
    ]
