# Generated by Django 4.0.3 on 2023-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0033_alter_analyticprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='analysis_unlock_duration',
            field=models.PositiveSmallIntegerField(blank=True, default=21),
        ),
        migrations.AddField(
            model_name='profile',
            name='analysis_unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
