# Generated by Django 4.0.3 on 2023-06-01 20:51

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0034_profile_analysis_unlock_duration_and_more'),
    ]

    operations = [
        TrigramExtension()
    ]
