# Generated by Django 4.0.3 on 2023-06-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0036_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepoint',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
