# Generated by Django 4.0.3 on 2023-06-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0038_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
