# Generated by Django 4.0.3 on 2023-07-31 17:34

import auth2.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0039_social_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(error_messages={'invalid_phone': 'Provide proper phone number format!', 'unique': 'Phone number registered already!'}, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be valid.', regex='^\\+\\d{2,3}\\s\\d{5}\\-\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='preference',
            name='notifications',
            field=models.JSONField(default={'fcm_token': None, 'general': True, 'new_follower': True, 'social_tap': True}, validators=[auth2.models.validate_notifications]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reachers',
            field=models.ManyToManyField(blank=True, related_name='reached_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
