# Generated by Django 4.0.3 on 2023-11-02 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0040_alter_phone_number_alter_preference_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('agent', models.CharField(max_length=100)),
                ('detected_platform', models.CharField(choices=[('Web', 'web'), ('Android', 'android'), ('Ios', 'ios'), ('Unknown', 'unknown')], max_length=10)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
