# Generated by Django 4.0.3 on 2023-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0041_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='agent',
            field=models.CharField(max_length=200),
        ),
    ]
