# Generated by Django 4.2.9 on 2024-01-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0042_alter_loginhistory_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
